macro(reason_define_colors)
  if("$ENV{SHELL}" MATCHES "bash|csh|zsh|fish")
    string(ASCII 27 ESC)
    set(c_reset    "${ESC}[m")
    set(c_bold     "${ESC}[1m")
    
    set(c_black    "${ESC}[30m")
    set(c_maroon   "${ESC}[31m")
    set(c_green    "${ESC}[32m")
    set(c_olive    "${ESC}[33m")
    set(c_navy     "${ESC}[34m")
    set(c_purple   "${ESC}[35m")
    set(c_teal     "${ESC}[36m")
    set(c_silver   "${ESC}[37m")
    set(c_gray     "${ESC}[90m")
    set(c_red      "${ESC}[91m")
    set(c_lime     "${ESC}[92m")
    set(c_yellow   "${ESC}[93m")
    set(c_blue     "${ESC}[94m")
    set(c_fuchsia  "${ESC}[95m")
    set(c_aqua     "${ESC}[96m")
    set(c_white    "${ESC}[97m")

    set(c_bblack   "${ESC}[1;30m")
    set(c_bmaroon  "${ESC}[1;31m")
    set(c_bgreen   "${ESC}[1;32m")
    set(c_bolive   "${ESC}[1;33m")
    set(c_bnavy    "${ESC}[1;34m")
    set(c_bpurple  "${ESC}[1;35m")
    set(c_bteal    "${ESC}[1;36m")
    set(c_bsilver  "${ESC}[1;37m")
    set(c_bgray    "${ESC}[1;90m")
    set(c_bred     "${ESC}[1;91m")
    set(c_blime    "${ESC}[1;92m")
    set(c_byellow  "${ESC}[1;93m")
    set(c_bblue    "${ESC}[1;94m")
    set(c_bfuchsia "${ESC}[1;95m")
    set(c_baqua    "${ESC}[1;96m")
    set(c_bwhite   "${ESC}[1;97m")
  else()
    set(c_reset    "")
    set(c_bold     "")
    
    set(c_black    "")
    set(c_maroon   "")
    set(c_green    "")
    set(c_olive    "")
    set(c_navy     "")
    set(c_purple   "")
    set(c_teal     "")
    set(c_silver   "")
    set(c_gray     "")
    set(c_red      "")
    set(c_lime     "")
    set(c_yellow   "")
    set(c_blue     "")
    set(c_fuchsia  "")
    set(c_aqua     "")
    set(c_white    "")

    set(c_bblack   "")
    set(c_bmaroon  "")
    set(c_bgreen   "")
    set(c_bolive   "")
    set(c_bnavy    "")
    set(c_bpurple  "")
    set(c_bteal    "")
    set(c_bsilver  "")
    set(c_bgray    "")
    set(c_bred     "")
    set(c_blime    "")
    set(c_byellow  "")
    set(c_bblue    "")
    set(c_bfuchsia "")
    set(c_baqua    "")
    set(c_bwhite   "")
  endif()
endmacro()
